apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-elasticsearch
  namespace: kube-system
  labels:
    k8s-app: fluentd-logging
spec:
   template:
     metadata:
       labels:
          name: fluentd
     spec:
        containers:
        - name: fluentd-elasticsearch
          image: gcr.io/google-containers/fluentd-elasticsearch:1.20
   selector:
       matchLabels:
          name: fluentd

