apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  ports:
   - port: 27017
     protocol: TCP
     targetPort: 27017
     nodePort: 32739
  selector:
     app: mongo
  type: NodePort  
